/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PessoasIndexRouteImport } from './routes/pessoas/index'
import { Route as ListarIndexRouteImport } from './routes/listar/index'
import { Route as LancamentoIndexRouteImport } from './routes/lancamento/index'
import { Route as AbaterIndexRouteImport } from './routes/abater/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PessoasIndexRoute = PessoasIndexRouteImport.update({
  id: '/pessoas/',
  path: '/pessoas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListarIndexRoute = ListarIndexRouteImport.update({
  id: '/listar/',
  path: '/listar/',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentoIndexRoute = LancamentoIndexRouteImport.update({
  id: '/lancamento/',
  path: '/lancamento/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbaterIndexRoute = AbaterIndexRouteImport.update({
  id: '/abater/',
  path: '/abater/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abater': typeof AbaterIndexRoute
  '/lancamento': typeof LancamentoIndexRoute
  '/listar': typeof ListarIndexRoute
  '/pessoas': typeof PessoasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abater': typeof AbaterIndexRoute
  '/lancamento': typeof LancamentoIndexRoute
  '/listar': typeof ListarIndexRoute
  '/pessoas': typeof PessoasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abater/': typeof AbaterIndexRoute
  '/lancamento/': typeof LancamentoIndexRoute
  '/listar/': typeof ListarIndexRoute
  '/pessoas/': typeof PessoasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/abater' | '/lancamento' | '/listar' | '/pessoas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/abater' | '/lancamento' | '/listar' | '/pessoas'
  id: '__root__' | '/' | '/abater/' | '/lancamento/' | '/listar/' | '/pessoas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbaterIndexRoute: typeof AbaterIndexRoute
  LancamentoIndexRoute: typeof LancamentoIndexRoute
  ListarIndexRoute: typeof ListarIndexRoute
  PessoasIndexRoute: typeof PessoasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pessoas/': {
      id: '/pessoas/'
      path: '/pessoas'
      fullPath: '/pessoas'
      preLoaderRoute: typeof PessoasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listar/': {
      id: '/listar/'
      path: '/listar'
      fullPath: '/listar'
      preLoaderRoute: typeof ListarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamento/': {
      id: '/lancamento/'
      path: '/lancamento'
      fullPath: '/lancamento'
      preLoaderRoute: typeof LancamentoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abater/': {
      id: '/abater/'
      path: '/abater'
      fullPath: '/abater'
      preLoaderRoute: typeof AbaterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbaterIndexRoute: AbaterIndexRoute,
  LancamentoIndexRoute: LancamentoIndexRoute,
  ListarIndexRoute: ListarIndexRoute,
  PessoasIndexRoute: PessoasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
